### ISSUE TITLE
I cannot access Kanban!

### ISSUE THREAD

**Issue by davesade** [do-team/documentation#3]
It says something regarding creating some token, I have no clue, how to do it! Who can help me?

**Comment by jurox83** [comment]
@davesade:
- Open your profile settings
- then go to "personal access tokens". -> https://github.com/settings/tokens
- Create a new one... 
- give it any name
- select "public_repo" or the full "repo" tree.
- save it
- copy the token hash
- insert it in the gh-board when you click on "log in"
